on: [push]
name: Install AppMap
jobs:
  install_appmap_job:
    runs-on: ubuntu-latest
    name: Install AppMap
    steps:
      - name: Checkout step
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'semeru'
          java-version: '11'
          cache: 'maven'
      - name: Install AppMap step
        uses: getappmap/install-appmap-action@v1-pre.1
        id: install-appmap
        with:
          verbose: true
      - name: Run tests
        run: ./mvnw --no-transfer-progress test
      - name: Build AppMap archive
        run: /tmp/appmap archive
      - name: Store the AppMap archive
        uses: actions/upload-artifact@v3
        with:
          name: archive
          path: .appmap/**/*.tar
